/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Trivial endpoint proving the mock API is installed and intercepting requests, and that type generation works end to end.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate with email and password
         * @description Validates the given credentials against the mock backend's seeded accounts (one administrator, one viewer) and, on success, issues an opaque bearer token together with the authenticated user record.
         */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate the current session
         * @description Invalidates the bearer token presented on the request, so a subsequent request with the same token is rejected as unauthorized.
         */
        post: operations["postAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the current session's user
         * @description Returns the user record associated with the bearer token presented on the request.
         */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregate dashboard statistics
         * @description Returns the complete dashboard payload in one request — headline counts, gross inventory value broken down per currency (never summed across currencies), ticket-status and event-status breakdowns, the next upcoming events and the nearly-sold-out tickets. Computed by the mock handler (`src/mocks/handlers/dashboard.ts`) from the in-memory db, the only version that survives a realistic dataset (PRD-007).
         */
        get: operations["getDashboardStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List events
         * @description Returns a page of events, filtered and sorted per the given query parameters. `startDateFrom`/`startDateTo` match events whose own `[startDate, endDate]` range overlaps the requested window, not events strictly contained within it — a long-running event must not be hidden from the list because it started before the window began.
         */
        get: operations["getEvents"];
        put?: never;
        /**
         * Create an event
         * @description Creates a new event from the given payload.
         */
        post: operations["postEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a bulk operation to several events
         * @description Applies one operation (`delete` or `archive`) to each of the given event identifiers, per-identifier, and reports a `BulkResult`: the identifiers that succeeded and, separately, those that failed each with a reason. Bulk `delete` reuses the same dependency-conflict rule as a single delete — a referenced event is reported as a per-identifier failure carrying the blocking count, not a top-level `409` (PRD-007). Rejected for a viewer with `403`.
         */
        post: operations["postEventsBulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch an event
         * @description Returns a single event by id.
         */
        get: operations["getEventsId"];
        put?: never;
        post?: never;
        /**
         * Delete an event
         * @description Deletes an event, unless another entity still depends on it — cascade deletion is deliberately not supported; the caller must resolve or remove the dependents first.
         */
        delete: operations["deleteEventsId"];
        options?: never;
        head?: never;
        /**
         * Partially update an event
         * @description Applies a partial update to an existing event.
         */
        patch: operations["patchEventsId"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List categories
         * @description Returns a page of ticket categories, filtered and sorted per the given query parameters.
         */
        get: operations["getCategories"];
        put?: never;
        /**
         * Create a category
         * @description Creates a new category from the given payload. Rejects a name that already exists (case-insensitively, ignoring leading/trailing whitespace) with a `409` carrying the `DUPLICATE_NAME` code.
         */
        post: operations["postCategories"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a bulk operation to several categories
         * @description Applies one operation to each of the given category identifiers, per-identifier, and reports a `BulkResult`. Bulk `delete` reuses the same dependency-conflict rule as a single delete — a category still referenced by tickets is reported as a per-identifier failure carrying the blocking count, not a top-level `409` (PRD-007). Categories have no lifecycle status, so `archive` is a no-op that reports each identifier as failed with an explanatory reason. Rejected for a viewer with `403`.
         */
        post: operations["postCategoriesBulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a category
         * @description Returns a single category by id.
         */
        get: operations["getCategoriesId"];
        put?: never;
        post?: never;
        /**
         * Delete a category
         * @description Deletes a category, unless a ticket still references it — cascade deletion is deliberately not supported; the caller must resolve or remove the dependent tickets first.
         */
        delete: operations["deleteCategoriesId"];
        options?: never;
        head?: never;
        /**
         * Partially update a category
         * @description Applies a partial update to an existing category. Rejects a name that already belongs to another category (case-insensitively, ignoring leading/trailing whitespace) with a `409` carrying the `DUPLICATE_NAME` code.
         */
        patch: operations["patchCategoriesId"];
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tickets
         * @description Returns a page of tickets, filtered and sorted per the given query parameters. Each returned ticket carries denormalised `eventName`/ `categoryName` alongside `eventId`/`categoryId`, resolved from the referenced event/category at read time.
         */
        get: operations["getTickets"];
        put?: never;
        /**
         * Create a ticket
         * @description Creates a new ticket from the given payload. Rejects an `eventId` or `categoryId` that does not resolve to an existing event/category with a `400` carrying a field error on the offending field.
         */
        post: operations["postTickets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a bulk operation to several tickets
         * @description Applies one operation (`delete` or `archive`) to each of the given ticket identifiers, per-identifier, and reports a `BulkResult`. A ticket is a leaf of the domain model — nothing references it — so bulk `delete` has no dependency-conflict case; the only per-identifier failure is a `NOT_FOUND`. `archive` sets each ticket's status to `archived`. Rejected for a viewer with `403`.
         */
        post: operations["postTicketsBulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a ticket
         * @description Returns a single ticket by id.
         */
        get: operations["getTicketsId"];
        put?: never;
        post?: never;
        /**
         * Delete a ticket
         * @description Deletes a ticket. Unlike an event or a category, a ticket is a leaf of the domain model — nothing references a ticket — so, unlike their delete operations, there is no dependency-conflict case here: deletion always succeeds once the ticket itself is found.
         */
        delete: operations["deleteTicketsId"];
        options?: never;
        head?: never;
        /**
         * Partially update a ticket
         * @description Applies a partial update to an existing ticket. Rejects an `eventId` or `categoryId` that does not resolve to an existing event/category with a `400` carrying a field error on the offending field.
         */
        patch: operations["patchTicketsId"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Body returned by `GET /health`. */
        HealthStatus: {
            /**
             * @description Literal liveness indicator.
             * @enum {string}
             */
            status: "ok";
        };
        /** @description Shared pagination envelope metadata. Every list endpoint returns a `data` array alongside a `meta` object of this shape. */
        PaginationMeta: {
            /** @description The current page number, 1-indexed. */
            page: number;
            /** @description The number of items returned per page. */
            perPage: number;
            /** @description The total number of items across all pages. */
            total: number;
            /** @description The total number of pages available. */
            totalPages: number;
        };
        /** @description A map of field name to a human-readable message describing why that field failed validation. */
        ValidationError: {
            [key: string]: string;
        };
        /** @description The shared error envelope returned by every failed request: a machine-readable code, a human message and, for validation failures, a per-field message map. */
        ErrorResponse: {
            /** @description Machine-readable error code, e.g. `VALIDATION_ERROR`, `UNAUTHORIZED`, `NOT_FOUND`, `CONFLICT`, `INTERNAL_ERROR`. `409` responses use a code more specific than the generic `CONFLICT` where the failure reason needs to be distinguishable by the client: `DUPLICATE_NAME` for a uniqueness violation (e.g. `POST /categories`/`PATCH /categories/{id}` on an existing name), versus the plain `CONFLICT` carried by `DependencyConflict` for a referential-integrity violation (e.g. deleting a category or event tickets still reference). Not modelled as a closed enum here because new codes are added by each owning slice as needed, same as `message`. */
            code: string;
            /** @description Human-readable summary of the failure. */
            message: string;
            /** @description Optional per-field validation messages. */
            errors?: components["schemas"]["ValidationError"];
        };
        /**
         * @description Lifecycle status of an Event.
         * @enum {string}
         */
        EventStatus: "draft" | "published" | "cancelled" | "completed";
        /**
         * @description Lifecycle status of a Ticket.
         * @enum {string}
         */
        TicketStatus: "draft" | "on_sale" | "sold_out" | "archived";
        /**
         * @description Supported currency codes (ISO 4217). Ticket prices are restricted to this set rather than a free-form string.
         * @enum {string}
         */
        Currency: "USD" | "EUR" | "GBP";
        /**
         * @description Sort direction for any `sort` parameter.
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /**
         * @description Response format for a list endpoint. `json` (the default) returns the paginated envelope; `csv` returns the full filtered result as `text/csv` (PRD-007).
         * @enum {string}
         */
        ListFormat: "json" | "csv";
        /**
         * @description Role granted to an authenticated user. `admin` may perform every operation; `viewer` may only read — every write endpoint rejects a viewer's token with `403` (PRD-007). Seeded with one account of each role (`src/mocks/db/fixtures.ts`).
         * @enum {string}
         */
        UserRole: "admin" | "viewer";
        /** @description An authenticated administrator or viewer of the portal. */
        User: {
            /** @description Opaque unique identifier. */
            id: string;
            /** @description Display name. */
            name: string;
            /** @description Login email address. */
            email: string;
            /** @description The role granted to this user. */
            role: components["schemas"]["UserRole"];
        };
        /** @description Body of `POST /auth/login`. */
        LoginRequest: {
            /** @description Login email address. */
            email: string;
            /** @description Login password. */
            password: string;
        };
        /** @description Body returned by a successful `POST /auth/login`. */
        LoginResponse: {
            /** @description Opaque bearer token to send as `Authorization: Bearer <token>` on subsequent requests. */
            token: string;
            /** @description The authenticated user record. */
            user: components["schemas"]["User"];
        };
        /** @description An event administrators create tickets against. */
        Event: {
            /** @description Opaque unique identifier. */
            id: string;
            /** @description Display name. */
            name: string;
            /** @description ISO 3166-1 alpha-2 country code, e.g. `US`. */
            country: string;
            /** @description Venue name. */
            venue: string;
            /**
             * Format: date
             * @description ISO 8601 date string, no time component.
             */
            startDate: string;
            /**
             * Format: date
             * @description ISO 8601 date string, no time component.
             */
            endDate: string;
            /** @description The event's lifecycle status. */
            status: components["schemas"]["EventStatus"];
            /**
             * Format: date-time
             * @description When the record was created.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When the record was last updated.
             */
            updatedAt: string;
        };
        /** @description The writable subset of an Event, shared by `POST /events` (full create) and `PATCH /events/{id}` (partial update). Deliberately carries no `required` list: OpenAPI's `required` is schema-wide, not per-operation, so a list here would force every field on a PATCH too, defeating "partial". Which fields are mandatory for create instead of update is enforced at runtime by the mock handler's `validate` function (`src/mocks/handlers/events.ts`) — do not add `required` back to this schema; add stricter runtime validation instead. */
        EventPayload: {
            /** @description Display name. */
            name?: string;
            /** @description ISO 3166-1 alpha-2 country code, e.g. `US`. */
            country?: string;
            /** @description Venue name. */
            venue?: string;
            /**
             * Format: date
             * @description ISO 8601 date string, no time component.
             */
            startDate?: string;
            /**
             * Format: date
             * @description ISO 8601 date string, no time component.
             */
            endDate?: string;
            /** @description The event's lifecycle status. */
            status?: components["schemas"]["EventStatus"];
        };
        /** @description Body returned by `GET /events`. */
        EventListResponse: {
            data: components["schemas"]["Event"][];
            /** @description Pagination metadata for the returned page. */
            meta: components["schemas"]["PaginationMeta"];
        };
        /** @description A ticket category (e.g. General Admission, VIP), shared across events. Names are unique case-insensitively and ignoring leading/trailing whitespace, enforced by the mock handler (`src/mocks/handlers/categories.ts`), not by this schema. */
        Category: {
            /** @description Opaque unique identifier. */
            id: string;
            /** @description Display name, unique across all categories. */
            name: string;
            /** @description Human-readable description of the category. */
            description: string;
            /**
             * Format: date-time
             * @description When the record was created.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When the record was last updated.
             */
            updatedAt: string;
        };
        /** @description The writable subset of a Category, shared by `POST /categories` (full create) and `PATCH /categories/{id}` (partial update). Deliberately carries no `required` list, for the same reason `EventPayload` does not: OpenAPI's `required` is schema-wide, not per-operation, so a list here would force `name` on a `PATCH` too, defeating "partial". Which fields are mandatory for create instead of update — and the uniqueness check — is enforced at runtime by the mock handler's `validate`/`conflictCheck` functions (`src/mocks/handlers/categories.ts`); do not add `required` back to this schema. */
        CategoryPayload: {
            /** @description Display name, unique across all categories. */
            name?: string;
            /** @description Human-readable description of the category. */
            description?: string;
        };
        /** @description Body returned by `GET /categories`. */
        CategoryListResponse: {
            data: components["schemas"]["Category"][];
            /** @description Pagination metadata for the returned page. */
            meta: components["schemas"]["PaginationMeta"];
        };
        /** @description A ticket offered for a given event and category. `price` is an integer in minor currency units (e.g. cents), never a float, so formatting to a locale-aware string only happens at the presentation boundary. `eventName`/`categoryName` are denormalised copies of the referenced event's/category's `name`, resolved at read time by the mock handler (`src/mocks/handlers/tickets.ts`) — not stored fields — so they always reflect the current name and never need a cascading update when an event or category is renamed. */
        Ticket: {
            /** @description Opaque unique identifier. */
            id: string;
            /** @description Display name. */
            name: string;
            /** @description Price in minor currency units (e.g. cents), never a float. */
            price: number;
            /** @description The currency this ticket is priced in. */
            currency: components["schemas"]["Currency"];
            /** @description Administrator-managed stock count, capped at 100,000. */
            quantity: number;
            /** @description The ticket's lifecycle status. */
            status: components["schemas"]["TicketStatus"];
            /** @description Id of the event this ticket belongs to. */
            eventId: string;
            /** @description Denormalised name of the referenced event, resolved at read time. */
            eventName: string;
            /** @description Id of the category this ticket belongs to. */
            categoryId: string;
            /** @description Denormalised name of the referenced category, resolved at read time. */
            categoryName: string;
            /**
             * Format: date-time
             * @description When the record was created.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description When the record was last updated.
             */
            updatedAt: string;
        };
        /** @description The writable subset of a Ticket, shared by `POST /tickets` (full create) and `PATCH /tickets/{id}` (partial update). Deliberately carries no `required` list, for the same reason `EventPayload`/ `CategoryPayload` do not: OpenAPI's `required` is schema-wide, not per-operation, so a list here would force every field on a `PATCH` too, defeating "partial". Which fields are mandatory for create instead of update — and the referential checks on `eventId`/ `categoryId` — is enforced at runtime by the mock handler's `validate` function (`src/mocks/handlers/tickets.ts`); do not add `required` back to this schema. */
        TicketPayload: {
            /** @description Display name. */
            name?: string;
            /** @description Price in minor currency units (e.g. cents), never a float. */
            price?: number;
            /** @description The currency this ticket is priced in. */
            currency?: components["schemas"]["Currency"];
            /** @description Administrator-managed stock count, capped at 100,000. */
            quantity?: number;
            /** @description The ticket's lifecycle status. */
            status?: components["schemas"]["TicketStatus"];
            /** @description Id of the event this ticket belongs to. */
            eventId?: string;
            /** @description Id of the category this ticket belongs to. */
            categoryId?: string;
        };
        /** @description Body returned by `GET /tickets`. */
        TicketListResponse: {
            data: components["schemas"]["Ticket"][];
            /** @description Pagination metadata for the returned page. */
            meta: components["schemas"]["PaginationMeta"];
        };
        /** @description The shared error envelope's `code` and `message`, extended with the blocking dependent entity's type and count, so a `409` on delete carries enough information for an administrator to act on it instead of a bare refusal. Declared standalone rather than via `allOf` because `ErrorResponse` is closed (`additionalProperties: false`), which would make the composition unsatisfiable. Introduced by the Events contract (PRD-004) and reused by the Categories contract (PRD-005). */
        DependencyConflict: {
            /** @description Always `CONFLICT` for a referential-integrity violation. */
            code: string;
            /** @description Human-readable summary of the failure. */
            message: string;
            /** @description The type of the blocking dependent entity, e.g. `ticket`. */
            entity: string;
            /** @description The number of dependent records blocking the operation. */
            count: number;
        };
        /** @description A monetary total for a single currency, in minor units (e.g. cents). The dashboard's gross inventory value is an array of these — one entry per currency present in the catalogue — and is NEVER summed across currencies into one figure. A single total mixing euros and pounds is not a number; it is a bug with a friendly face (PRD-007). The presentation layer formats each entry with its own currency. */
        CurrencyTotal: {
            /** @description The currency this total is denominated in. */
            currency: components["schemas"]["Currency"];
            /** @description The total value in this currency, in minor units (e.g. cents), never a float — mirrors `Ticket.price`. */
            totalMinorUnits: number;
        };
        /** @description The number of records carrying a given lifecycle status. Used for both the ticket-status and event-status breakdowns on the dashboard. `status` is a bare string rather than a specific status enum because the same shape serves both Event and Ticket statuses; the owning breakdown array constrains which values appear. */
        StatusBreakdown: {
            /** @description The lifecycle status value, e.g. `draft` or `on_sale`. */
            status: string;
            /** @description The number of records carrying this status. */
            count: number;
        };
        /** @description The complete aggregate payload for `GET /dashboard/stats`, computed in one request by the mock handler (`src/mocks/handlers/dashboard.ts`) rather than by reducing lists in the browser — the only version that survives a realistic dataset (PRD-007). Gross inventory value is broken down per currency and never summed across currencies. */
        DashboardStats: {
            /** @description Total number of events in the catalogue. */
            totalEvents: number;
            /** @description Number of events currently running — those whose lifecycle status is `published`. */
            runningEvents: number;
            /** @description Total number of tickets in the catalogue. */
            totalTickets: number;
            /** @description Sum of every ticket's stock quantity across the catalogue. */
            totalAvailableQuantity: number;
            /** @description Gross inventory value (price × quantity) broken down per currency. Never a single cross-currency total — see `CurrencyTotal`. */
            grossInventoryValue: components["schemas"]["CurrencyTotal"][];
            /** @description Ticket count per `TicketStatus`. */
            ticketStatusBreakdown: components["schemas"]["StatusBreakdown"][];
            /** @description Event count per `EventStatus`. */
            eventStatusBreakdown: components["schemas"]["StatusBreakdown"][];
            /** @description The next events starting, soonest first — events whose start date is today or later, capped at a handler-defined limit. */
            upcomingEvents: components["schemas"]["Event"][];
            /** @description Tickets whose stock is nearly exhausted — quantity at or below the handler's documented `NEARLY_SOLD_OUT_MAX_QUANTITY` threshold, and not already `sold_out`/`archived` — lowest stock first, capped at a handler-defined limit. */
            nearlySoldOutTickets: components["schemas"]["Ticket"][];
        };
        /**
         * @description The operation a bulk request applies to each of its identifiers. `delete` removes each record (subject to the same dependency-conflict rules as a single delete); `archive` sets each record's status to its archived/completed terminal state.
         * @enum {string}
         */
        BulkOperation: "delete" | "archive";
        /** @description Body of a bulk endpoint (`POST /events/bulk`, `POST /categories/bulk`, `POST /tickets/bulk`): a list of record identifiers and the single operation to apply to each. A server-side loop rather than N client round trips, so partial failure can be reported coherently (PRD-007). */
        BulkRequest: {
            /** @description The identifiers to apply the operation to. At most 100 per request. */
            ids: string[];
            /** @description The operation applied to each identifier. */
            operation: components["schemas"]["BulkOperation"];
        };
        /** @description One failed identifier within a `BulkResult`, carrying why it failed. A dependency-conflict failure (a referenced event/category, same rule as a single delete) additionally carries the blocking dependent count, so the UI can report it per record rather than as a top-level `409`. */
        BulkFailure: {
            /** @description The identifier that failed. */
            id: string;
            /** @description Machine-readable failure code, e.g. `NOT_FOUND` or `CONFLICT` (a dependency conflict) — mirrors `ErrorResponse.code`. */
            code: string;
            /** @description Human-readable explanation of the failure. */
            reason: string;
            /** @description For a dependency conflict only: the number of dependent records blocking the operation on this identifier. Absent otherwise. */
            count?: number;
        };
        /** @description Body returned by a bulk endpoint: the identifiers that succeeded and, separately, the identifiers that failed each with a reason. Partial success is the expected case, not an edge case (PRD-007), so both arrays are always present (either may be empty). */
        BulkResult: {
            /** @description Identifiers the operation was applied to successfully. */
            succeeded: string[];
            /** @description Identifiers the operation could not be applied to, each with a reason. */
            failed: components["schemas"]["BulkFailure"][];
        };
    };
    responses: {
        /** @description The request failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The session is absent or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The session is valid but the authenticated user lacks permission for this operation — a viewer attempting a write (PRD-007). Distinct from `401`: the caller is authenticated, so this is a permission failure, not a session failure, and the response interceptor notifies without signing the user out. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No resource exists with the given identifier. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request conflicts with the current state of the resource, e.g. a referential-integrity violation. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description An unexpected or forced failure occurred while handling the request. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The full filtered and sorted result as CSV (`format=csv`) — every matching record, not just the current page. A `Content-Disposition` header carries a filename combining the entity and the export date (e.g. `attachment; filename="tickets-2026-09-23.csv"`). Money is a decimal with its currency in a separate column, dates are ISO-8601, and references appear by name; comma/quote/newline field values are escaped RFC-4180 style. */
        CsvExport: {
            headers: {
                /** @description Carries the download filename combining the entity and export date. */
                "Content-Disposition"?: string;
                [name: string]: unknown;
            };
            content: {
                "text/csv": string;
            };
        };
    };
    parameters: {
        /** @description Free-text search applied across an endpoint's declared searchable fields. */
        search: string;
        /** @description Field name to sort by. Valid values are declared by the owning endpoint. */
        sort: string;
        /** @description Sort direction, paired with `sort`. */
        order: components["schemas"]["SortOrder"];
        /** @description 1-indexed page number. */
        page: number;
        /** @description Number of items per page. A value above the maximum is clamped to it; a non-integer value falls back to the default. */
        perPage: number;
        /** @description Response format. Omit (or `json`) for the paginated JSON list envelope. `csv` returns the FULL filtered and sorted result — every matching record, not just the current page — as `text/csv` with a `Content-Disposition` filename, so an export reflects exactly the query the list is showing (PRD-007). `page`/`perPage` are ignored for `csv`. */
        format: components["schemas"]["ListFormat"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Credentials were valid; a session token was issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    postAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session was invalidated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDashboardStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The aggregate dashboard statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardStats"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getEvents: {
        parameters: {
            query?: {
                /** @description Free-text search applied across an endpoint's declared searchable fields. */
                search?: components["parameters"]["search"];
                /** @description Field name to sort by. Valid values are declared by the owning endpoint. */
                sort?: components["parameters"]["sort"];
                /** @description Sort direction, paired with `sort`. */
                order?: components["parameters"]["order"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["page"];
                /** @description Number of items per page. A value above the maximum is clamped to it; a non-integer value falls back to the default. */
                perPage?: components["parameters"]["perPage"];
                /** @description Filters to events with this exact lifecycle status. */
                status?: components["schemas"]["EventStatus"];
                /** @description Filters to events with this exact ISO 3166-1 alpha-2 country code. */
                country?: string;
                /** @description Lower bound of the requested date window, inclusive. Matched by overlap against each event's own `[startDate, endDate]` range, not containment. */
                startDateFrom?: string;
                /** @description Upper bound of the requested date window, inclusive. Matched by overlap against each event's own `[startDate, endDate]` range, not containment. */
                startDateTo?: string;
                /** @description Response format. Omit (or `json`) for the paginated JSON list envelope. `csv` returns the FULL filtered and sorted result — every matching record, not just the current page — as `text/csv` with a `Content-Disposition` filename, so an export reflects exactly the query the list is showing (PRD-007). `page`/`perPage` are ignored for `csv`. */
                format?: components["parameters"]["format"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of events (default), or — when `format=csv` — the full filtered result as `text/csv` (see `x-csv-export`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                    "text/csv": string;
                };
            };
            "x-csv-export": components["responses"]["CsvExport"];
        };
    };
    postEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPayload"];
            };
        };
        responses: {
            /** @description The event was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    postEventsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkRequest"];
            };
        };
        responses: {
            /** @description The per-identifier outcome of the bulk operation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getEventsId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteEventsId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The event cannot be deleted because another entity (e.g. a ticket) still references it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyConflict"];
                };
            };
        };
    };
    patchEventsId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventPayload"];
            };
        };
        responses: {
            /** @description The updated event. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCategories: {
        parameters: {
            query?: {
                /** @description Free-text search applied across an endpoint's declared searchable fields. */
                search?: components["parameters"]["search"];
                /** @description Field name to sort by. Valid values are declared by the owning endpoint. */
                sort?: components["parameters"]["sort"];
                /** @description Sort direction, paired with `sort`. */
                order?: components["parameters"]["order"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["page"];
                /** @description Number of items per page. A value above the maximum is clamped to it; a non-integer value falls back to the default. */
                perPage?: components["parameters"]["perPage"];
                /** @description Response format. Omit (or `json`) for the paginated JSON list envelope. `csv` returns the FULL filtered and sorted result — every matching record, not just the current page — as `text/csv` with a `Content-Disposition` filename, so an export reflects exactly the query the list is showing (PRD-007). `page`/`perPage` are ignored for `csv`. */
                format?: components["parameters"]["format"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of categories (default), or — when `format=csv` — the full filtered result as `text/csv` (see `x-csv-export`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryListResponse"];
                    "text/csv": string;
                };
            };
            "x-csv-export": components["responses"]["CsvExport"];
        };
    };
    postCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryPayload"];
            };
        };
        responses: {
            /** @description The category was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A category with this name already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postCategoriesBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkRequest"];
            };
        };
        responses: {
            /** @description The per-identifier outcome of the bulk operation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getCategoriesId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteCategoriesId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The category cannot be deleted because one or more tickets still reference it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyConflict"];
                };
            };
        };
    };
    patchCategoriesId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryPayload"];
            };
        };
        responses: {
            /** @description The updated category. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Another category already has this name. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTickets: {
        parameters: {
            query?: {
                /** @description Free-text search applied across an endpoint's declared searchable fields. */
                search?: components["parameters"]["search"];
                /** @description Field name to sort by. Valid values are declared by the owning endpoint. */
                sort?: components["parameters"]["sort"];
                /** @description Sort direction, paired with `sort`. */
                order?: components["parameters"]["order"];
                /** @description 1-indexed page number. */
                page?: components["parameters"]["page"];
                /** @description Number of items per page. A value above the maximum is clamped to it; a non-integer value falls back to the default. */
                perPage?: components["parameters"]["perPage"];
                /** @description Filters to tickets belonging to this exact event id. */
                eventId?: string;
                /** @description Filters to tickets belonging to this exact category id. */
                categoryId?: string;
                /** @description Filters to tickets with this exact lifecycle status. */
                status?: components["schemas"]["TicketStatus"];
                /** @description Filters to tickets priced in this exact currency. */
                currency?: components["schemas"]["Currency"];
                /** @description Lower bound (inclusive) on price, in minor currency units. */
                priceMin?: number;
                /** @description Upper bound (inclusive) on price, in minor currency units. */
                priceMax?: number;
                /** @description Response format. Omit (or `json`) for the paginated JSON list envelope. `csv` returns the FULL filtered and sorted result — every matching record, not just the current page — as `text/csv` with a `Content-Disposition` filename, so an export reflects exactly the query the list is showing (PRD-007). `page`/`perPage` are ignored for `csv`. */
                format?: components["parameters"]["format"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of tickets (default), or — when `format=csv` — the full filtered result as `text/csv` (see `x-csv-export`). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketListResponse"];
                    "text/csv": string;
                };
            };
            "x-csv-export": components["responses"]["CsvExport"];
        };
    };
    postTickets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketPayload"];
            };
        };
        responses: {
            /** @description The ticket was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    postTicketsBulk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkRequest"];
            };
        };
        responses: {
            /** @description The per-identifier outcome of the bulk operation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTicketsId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ticket record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteTicketsId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ticket was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    patchTicketsId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketPayload"];
            };
        };
        responses: {
            /** @description The updated ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
