/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Trivial endpoint proving the mock API is installed and intercepting requests, and that type generation works end to end.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate with email and password
         * @description Validates the given credentials against the mock backend's seeded administrator account and, on success, issues an opaque bearer token together with the authenticated user record.
         */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate the current session
         * @description Invalidates the bearer token presented on the request, so a subsequent request with the same token is rejected as unauthorized.
         */
        post: operations["postAuthLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the current session's user
         * @description Returns the user record associated with the bearer token presented on the request.
         */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Body returned by `GET /health`. */
        HealthStatus: {
            /**
             * @description Literal liveness indicator.
             * @enum {string}
             */
            status: "ok";
        };
        /** @description Shared pagination envelope metadata. Every list endpoint returns a `data` array alongside a `meta` object of this shape. */
        PaginationMeta: {
            /** @description The current page number, 1-indexed. */
            page: number;
            /** @description The number of items returned per page. */
            perPage: number;
            /** @description The total number of items across all pages. */
            total: number;
            /** @description The total number of pages available. */
            totalPages: number;
        };
        /** @description A map of field name to a human-readable message describing why that field failed validation. */
        ValidationError: {
            [key: string]: string;
        };
        /** @description The shared error envelope returned by every failed request: a machine-readable code, a human message and, for validation failures, a per-field message map. */
        ErrorResponse: {
            /** @description Machine-readable error code, e.g. `VALIDATION_ERROR`, `UNAUTHORIZED`, `NOT_FOUND`, `CONFLICT`, `INTERNAL_ERROR`. */
            code: string;
            /** @description Human-readable summary of the failure. */
            message: string;
            /** @description Optional per-field validation messages. */
            errors?: components["schemas"]["ValidationError"];
        };
        /**
         * @description Lifecycle status of an Event.
         * @enum {string}
         */
        EventStatus: "draft" | "published" | "cancelled" | "completed";
        /**
         * @description Lifecycle status of a Ticket.
         * @enum {string}
         */
        TicketStatus: "draft" | "on_sale" | "sold_out" | "archived";
        /**
         * @description Supported currency codes (ISO 4217). Ticket prices are restricted to this set rather than a free-form string.
         * @enum {string}
         */
        Currency: "USD" | "EUR" | "GBP";
        /**
         * @description Sort direction for any `sort` parameter.
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        /**
         * @description Role granted to an authenticated user. Currently seeded with a single administrator role; extended with a viewer role by PRD-007.
         * @enum {string}
         */
        UserRole: "admin";
        /** @description An authenticated administrator or viewer of the portal. */
        User: {
            /** @description Opaque unique identifier. */
            id: string;
            /** @description Display name. */
            name: string;
            /** @description Login email address. */
            email: string;
            /** @description The role granted to this user. */
            role: components["schemas"]["UserRole"];
        };
        /** @description Body of `POST /auth/login`. */
        LoginRequest: {
            /** @description Login email address. */
            email: string;
            /** @description Login password. */
            password: string;
        };
        /** @description Body returned by a successful `POST /auth/login`. */
        LoginResponse: {
            /** @description Opaque bearer token to send as `Authorization: Bearer <token>` on subsequent requests. */
            token: string;
            /** @description The authenticated user record. */
            user: components["schemas"]["User"];
        };
    };
    responses: {
        /** @description The request failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The session is absent or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No resource exists with the given identifier. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request conflicts with the current state of the resource, e.g. a referential-integrity violation. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description An unexpected or forced failure occurred while handling the request. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Free-text search applied across an endpoint's declared searchable fields. */
        search: string;
        /** @description Field name to sort by. Valid values are declared by the owning endpoint. */
        sort: string;
        /** @description Sort direction, paired with `sort`. */
        order: components["schemas"]["SortOrder"];
        /** @description 1-indexed page number. */
        page: number;
        /** @description Number of items per page. */
        perPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Credentials were valid; a session token was issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    postAuthLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session was invalidated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user record. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
