/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDataTable: typeof import('./../../src/components/data-table/AppDataTable.vue')['default']
    BulkResultDialog: typeof import('./../../src/components/BulkResultDialog.vue')['default']
    CategoryModal: typeof import('./../../src/views/categories/components/CategoryModal.vue')['default']
    Compute: typeof import('./../../src/components/Compute.vue')['default']
    CurrencyInput: typeof import('./../../src/components/CurrencyInput.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyNoDataIllustration: typeof import('./../../src/components/illustrations/EmptyNoDataIllustration.vue')['default']
    EmptyNoMatchesIllustration: typeof import('./../../src/components/illustrations/EmptyNoMatchesIllustration.vue')['default']
    EventForm: typeof import('./../../src/views/events/components/EventForm.vue')['default']
    ForbiddenIllustration: typeof import('./../../src/components/illustrations/ForbiddenIllustration.vue')['default']
    Icon: typeof import('./../../src/features/platform/icons/components/Icon.vue')['default']
    ListToolbar: typeof import('./../../src/components/data-table/ListToolbar.vue')['default']
    LoadFailedIllustration: typeof import('./../../src/components/illustrations/LoadFailedIllustration.vue')['default']
    Modals: typeof import('./../../src/features/platform/modals/components/Modals.vue')['default']
    NotFoundIllustration: typeof import('./../../src/components/illustrations/NotFoundIllustration.vue')['default']
    PageHeader: typeof import('./../../src/components/PageHeader.vue')['default']
    RemoteSelect: typeof import('./../../src/components/RemoteSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusDistributionBar: typeof import('./../../src/views/dashboard/components/StatusDistributionBar.vue')['default']
    StatusTag: typeof import('./../../src/components/StatusTag.vue')['default']
    TicketForm: typeof import('./../../src/views/tickets/components/TicketForm.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
